# Define required macros here
SHELL = /bin/sh

CFLAG = -Wall -g
CC = g++
INCLUDE =
LIBS = -lm

all:
	sudo apt-get install libreadline-dev
	${CC} ${CFLAGS} a1que2.cpp -lreadline -o a1que2.o

clean:
	rm -f *.o *.o

