Sample input and output:

Input Command:
./mydict_add.sh

Output:
Enter the new word: ample
Enter the meaning: enough or more than enough; plentiful.
The word has been successfully added to your dictionary!!

Enter the new word: apple
Enter the meaning: the round fruit of a tree of the rose family, which typically
has thin green or red skin and crisp flesh.The word already exist in your dictionary.




Input Command:
./mydict_search.sh

Output:
Enter the word: ample
Ample: enough or more than enough; plentiful.

Enter the word: ambiguous
The word does not exist in your dictionary.
